[package]
name = "strid-macros"
description = "Implementation macros for the `strid` crate"
version = "5.0.0"
authors.workspace = true
edition.workspace = true
readme = "README.md"
license.workspace = true
repository.workspace = true

[package.metadata]

[package.metadata."docs.rs"]
rustdoc-args = ["--html-in-header", "arborium-header.html"]

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
unsynn.workspace = true

[dev-dependencies]
pretty_assertions = "1.4.1"
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
