[package]
name = "strid-examples"
description = "Examples demonstrating usage of the `strid` crate"
keywords = [ "string", "newtype", "validation", "normalization" ]
categories = [ "data-structures", "rust-patterns" ]
version = "8.0.1"
authors.workspace = true
edition.workspace = true
readme = "../../README.md"
license.workspace = true
repository.workspace = true
publish = true

[features]
# These features are placeholders for when facet adds support for these types
bytestring-facet = []
compact_str-facet = []
smartstring-facet = []

[dependencies]
strid = { version = "8.0.1", path = "../strid" }
facet.workspace = true
bytes = "1"
bytestring = { version = "1.5", features = [ "serde" ] }
serde = { version = "1", features = [ "derive" ] }
smartstring = { version = "1", features = [ "serde" ] }
compact_str = { version = "0.9", features = [ "serde" ] }
